# -*- coding: utf-8 -*-
"""Web_semantics_python_modifs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZtwARPes_GJ4WqHswAmca4bAR81OGj1
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Data/'
excel_file = pd.read_excel(path + 'excel_web.xlsx')

"""# Cleaning

"""

excel_file=excel_file.drop(['URL et ID Onisep','université de rattachement ID et URL Onisep','établissements liés URL et ID Onisep'],axis=1)

excel_file

excel_file.info()

all_columns = list(excel_file) # Creates list of all column headers, on change tout en string
for i in all_columns:
  excel_file[i] = excel_file[i].astype(str)

#on garde longitude & latitude en float
excel_file['longitude (X)'] = pd.to_numeric(excel_file['longitude (X)'])
excel_file['latitude (Y)'] = pd.to_numeric(excel_file['latitude (Y)'])

for i in range(len(excel_file['arrondissement'])): #maintenant on change le borough en int et on se débarasse des caractères non numeriques
  numeric_filter = filter(str.isdigit, excel_file['arrondissement'][i])
  excel_file['arrondissement'][i] = "".join(numeric_filter)

excel_file['arrondissement'] = excel_file['arrondissement'].replace('nan','0').replace('','0').astype(int) #on convertit en int

#on merge les colonnes d'établissements liés 
excel_file['Linked School'] = excel_file[['université de rattachement libellé', 'établissements liés libellés']].agg('-'.join, axis=1)

excel_file=excel_file.drop(['université de rattachement libellé', 'établissements liés libellés'],axis=1)

excel_file=excel_file.drop(['boîte postale'],axis=1)

#on merge les colonnes d'établissements liés 
excel_file['address'] = excel_file[['adresse', 'CP']].agg(','.join, axis=1)

excel_file=excel_file.drop(['adresse', 'CP'],axis=1)

"""# Let's change the name of the columns"""

dictionnary_columns= {
    'code UAI':'UAI',
    'n° SIRET':'SIRET',
    "type d'établissement":"school's type",
    'nom':'name',
    'sigle':'acronym',
    'statut':'statut',
    'tutelle':'Ministry',
    'address':'address',
    'commune':'city',
    'téléphone':'telephone',
    'arrondissement':'borough',
    'académie':'Academy',
    'région':'region',
    'longitude (X)':'longitude',
    'latitude (Y)':'latitude',
    'Linked School':'Linked Schools'


}

excel_file.columns = excel_file.columns.to_series().map(dictionnary_columns)

excel_file

"""# Generate RDF with RDFLib"""

!pip install rdflib

from rdflib import URIRef, BNode, Literal

